apiVersion: v1
data:
  config.yaml: |+
    configVersion: v1
    schedule:
    - crontab: "*/2 * * * *"
      allowFailure: true

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: so-config
