apiVersion: v1
kind: ServiceAccount
metadata:
  name: shell-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: shell-operator-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shell-operator-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: shell-operator
  namespace: default
roleRef:
  kind: Role
  name: shell-operator-role
  apiGroup: rbac.authorization.k8s.io

